export const WS_CONNECTION_START = 'WS_CONNECTION_START' as const;
export const WS_CONNECTION_SUCCESS = 'WS_CONNECTION_SUCCESS' as const;
export const WS_CONNECTION_ERROR = 'WS_CONNECTION_ERROR' as const;
export const WS_CONNECTION_CLOSED = 'WS_CONNECTION_CLOSED' as const;
export const WS_GET_MESSAGE_ORDERS_ALL = 'WS_GET_MESSAGE_ORDERS_ALL' as const;
export const WS_GET_MESSAGE_ORDERS_USER = 'WS_GET_MESSAGE_ORDERS_USER' as const;
